$# Layup Lib 20130730 API 20130730 File 20121016
$# Message file opened
$# Composites Modeler for Abaqus/CAE release 6.19.0.02 2019.0415
$# Deleting all laminates.
$# Reinitialisation completed
$# Nodes created
$# Elements created
$# Mesh created
$# A total of 1 subdomains were identified.
$#  subdomain   1 contains   4824 facets of area 15694.7
$# Save Layup file 'G:/SIMULIA/workspace/03-Mechanical mechanism analysis/add-on example/banqiu/Part-1.Layup' with detail=0 compress=0
$# Layup file saved
$# Simulating ply '0 degree'
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Extension iteration: 1
$# Number of new unique points: 4
$# Number of new unique points: 0
$# Updating Outline
$#  First outline point moved from (-1,0) to (-1,-1)
$# Updating Outline
$# Number of new edge points: 16
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 24
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 32
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 40
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 48
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 56
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 64
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 72
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 80
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-10,-10) to (-11,-9)
$# Number of new edge points: 76
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-11,-9) to (-12,-8)
$# Number of new edge points: 68
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-12,-8) to (-13,-7)
$# Number of new edge points: 60
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-13,-7) to (-14,-6)
$# Number of new edge points: 52
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-14,-6) to (-15,-4)
$# Number of new edge points: 36
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-15,-4) to (-16,-3)
$# Number of new edge points: 28
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 0
$# Number of unterminated points: 0
$# Pattern bounds: -16  16 -16  16   0
$#  Outline sizes: 0:128
$# (...repeated 2 times...)
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Simulating ply ''
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Extension iteration: 1
$# Number of new unique points: 4
$# Number of new unique points: 0
$# Updating Outline
$#  First outline point moved from (-1,0) to (-1,-1)
$# Updating Outline
$# Number of new edge points: 16
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 24
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 32
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 40
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 48
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 56
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 64
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 72
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 80
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-10,-10) to (-11,-9)
$# Number of new edge points: 76
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-11,-9) to (-12,-8)
$# Number of new edge points: 68
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-12,-8) to (-13,-7)
$# Number of new edge points: 60
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-13,-7) to (-14,-6)
$# Number of new edge points: 52
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-14,-6) to (-15,-4)
$# Number of new edge points: 36
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-15,-4) to (-16,-3)
$# Number of new edge points: 28
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 0
$# Number of unterminated points: 0
$# Pattern bounds: -16  16 -16  16   0
$#  Outline sizes: 0:128
$# (...repeated 2 times...)
$# Simulating ply '45 degree'
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Extension iteration: 1
$# Number of new unique points: 4
$# Number of new unique points: 0
$# Updating Outline
$#  First outline point moved from (-1,0) to (-1,-1)
$# Updating Outline
$# Number of new edge points: 16
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 24
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 32
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 40
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 48
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 56
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 64
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 72
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 80
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-10,-10) to (-11,-9)
$# Number of new edge points: 76
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-11,-9) to (-12,-8)
$# Number of new edge points: 68
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-12,-8) to (-13,-7)
$# Number of new edge points: 60
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-13,-7) to (-14,-6)
$# Number of new edge points: 52
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-14,-6) to (-15,-4)
$# Number of new edge points: 36
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-15,-4) to (-16,-3)
$# Number of new edge points: 28
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 0
$# Number of unterminated points: 0
$# Pattern bounds: -16  16 -16  16   0
$#  Outline sizes: 0:128
$# (...repeated 2 times...)
$# Simulating ply 'jiqiang'
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Extension iteration: 1
$# Number of new unique points: 4
$# Number of new unique points: 0
$# Updating Outline
$#  First outline point moved from (-1,0) to (-1,-1)
$# Updating Outline
$# Number of new edge points: 16
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 24
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 32
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 40
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 48
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 56
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 64
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 72
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-9,-9) to (-10,-8)
$# Number of new edge points: 68
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-10,-8) to (-11,-7)
$# Number of new edge points: 60
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-11,-7) to (-12,-6)
$# Number of new edge points: 52
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-12,-6) to (-13,-5)
$# Number of new edge points: 44
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-13,-5) to (-14,-4)
$# Number of new edge points: 36
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-14,-4) to (-15,-3)
$# Number of new edge points: 28
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-15,-3) to (-16,-2)
$# Number of new edge points: 20
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 20
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-17,-2) to (-18,-1)
$# Number of new edge points: 12
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-18,-1) to (-19,0)
$# Number of new edge points: 4
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 0
$# Number of unterminated points: 0
$# Pattern bounds: -19  19 -19  19   0
$#  Outline sizes: 0:152
$# (...repeated 2 times...)
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Deleting ply layup.
$# Ply '0 degree' added to layup
$# Ply '45 degree' added to layup
$# Ply 'jiqiang' added to layup
$# Ply '45 degree' added to layup
$# Ply '0 degree' added to layup
$# Layup 'Layup' created
$# Simulating ply ''
$# Start point [0,50,0] direction <-0,-1,-0> wobble 0.3
$#  iter  0 point [0,50,0] on elem 154 at dist 0 chosen
$# Extension iteration: 1
$# Number of new unique points: 4
$# Number of new unique points: 0
$# Updating Outline
$#  First outline point moved from (-1,0) to (-1,-1)
$# Updating Outline
$# Number of new edge points: 16
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 24
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 32
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 40
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 48
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 56
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 64
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 72
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 80
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-10,-10) to (-11,-9)
$# Number of new edge points: 76
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-11,-9) to (-12,-8)
$# Number of new edge points: 68
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-12,-8) to (-13,-7)
$# Number of new edge points: 60
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-13,-7) to (-14,-6)
$# Number of new edge points: 52
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-14,-6) to (-15,-4)
$# Number of new edge points: 36
$# Updating Outline
$# (...repeated 2 times...)
$#  First outline point moved from (-15,-4) to (-16,-3)
$# Number of new edge points: 28
$# Updating Outline
$# (...repeated 2 times...)
$# Number of new edge points: 0
$# Number of unterminated points: 0
$# Pattern bounds: -16  16 -16  16   0
$#  Outline sizes: 0:128
$# (...repeated 2 times...)
$# Deleting ply layup.
$# Ply '0 degree' added to layup
$# Ply '90 degree' added to layup
$# Ply 'jiqiang' added to layup
$# Ply '90 degree' added to layup
$# Ply '0 degree' added to layup
$# Deleting all laminates.
$# (...repeated 2 times...)
$# Save Layup file 'G:/SIMULIA/workspace/03-Mechanical mechanism analysis/add-on example/banqiu/Part-1.Layup' with detail=0 compress=0
$# Layup file saved
$# Save Layup file 'G:/SIMULIA/workspace/03-Mechanical mechanism analysis/add-on example/banqiu/Part-1.Layup' with detail=0 compress=0
$# Layup file saved
